### ISSUE TITLE
User can give 5 stars of rating to a song.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#11]
## Motivation
Users need the ability to record their feedback for a song.

## Tasks
- [x] Find star and bullet icons from Material-UI and import them into a 5-stars rating component.
- [x] Rating component should have an initial state of 0 (no rating).
- [x] Clicking on a bullet should update the initial state and cause stars up until that rating to be rendered instead of a bullet.
- [x] Test rating component in isolation to ensure its behavior works as planned.
- [x] Import rating component into the `songs` view and render it once inline with each song.
- [x] Clicking on the rating next to each song should render the correct number of stars for each song.
- [x] Create an express.js route that receives a user id, playlist id, song id, and rating, and creates/updates the rating for a particular song in a MongoDB database. 
- [x] Test the route with HTTPie.
- [x] Clicking on a rating next to a song should initiate a fetch request to the given express route that updates the mongodb.
- [x] Upon initial render of a playlist, sends a fetch request to express that requests the playlist information from Spotify and adds the ratings from the MongoDB database.
