### ISSUE TITLE
User can filter ratings for shared playlists by user.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#12]
# Motivation
Users will want to see different ratings from various users of the app.

# Tasks
- [x] Top of a playlist's view should display the name of the playlist on the left-hand side.
- [ ] Info-bar should display a drop down menu that defaults to `Your Ratings`.
- [ ] Improve styling of drop down menu.
- [ ] Info-bar drop down should contain user display names for each user that has shared or received the playlist with/from the current user.
- [ ] Fetch call to ratings database should be refactored to also accept a `userId`.
- [ ] `songs` view Fetch call should initialize by sending the current userId and re-rendering the view with the current user's ratings.
- [ ] Selecting a different user from the drop-down should initiate a new fetch call with that user's userid and re-render the view.
