### ISSUE TITLE
User can view their avatar.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#19]
## Motivation
Users need to be able to see their avatar while working on the app.

## Tasks
- [ ] Add user image to the information stored in MongoDB.
- [ ] Create a React Component to hold the user image.
- [ ] Embed the user image into the component.
- [ ] Component should be positioned in the upper right hand corner of the screen.
- [ ] Improve visual styling of the component.
