### ISSUE TITLE
User can return to view playlists.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#22]
## Motivation 
User may decide to look at a different playlist after viewing one.

## Tasks
- [x] Locate icon with back arrow within MaterialUI and import it into the PageHeader view.
- [x] Conditionally render the back arrow depending on whether or not view is "songs".
- [x] Ensure icon is placed correctly in the upper left hand corner of the app.
- [x] _Removed outdated CSS class._
- [x] Add a viewPlaylists function in app.js to return the app state to the playlists view that is passed to PageHeader as a prop. 
- [x] Add an onClick event listener to the icon that calls the viewPlaylists function when clicked.
- [x] Verify that clicking the icon returns the user to the playlists view and clears the selectedPlaylist in app state.
