### ISSUE TITLE
User can open a playlist shared by another user.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#31]
# Motivation
Users will want to see all the playlists that have been shared with them, and add them to their library.

# Tasks
- [x] Shares in the MongoDB database should have a `seen` attribute initially set to false.
- [x] Create Express.js path that returns the number of unseen shares for a user.
- [x] Upon `app.js` mount, MongoDB database should be queried for the number of unseen shares for that user.
- [x] The number of unseen shares should be passed  as props to `page-header.js`.
- [x] _Destructure this.state and this in app.js_
- [x] Import a badge component from Material-UI into `page-header.js`
- [x] If there are more than 0 unseen shares, render a badge component above the user's avatar.
- [x] Badge should not influence placement of User Avatar; improve styling.
- [x] Add a click event listener to the User's Avatar to update the app's `view` to `shares`.
- [x] Move click event listener to containing Badge element if there are unseen playlists.
- [x] `Shares` view should contain a back button to the playlists view.
- [x] Create Express.js path that returns all shares for a given user.
- [x] Upon `shares` mount, it should query the MongoDB database for all shares to that user.
- [x] Shares in the database should include sendingUserName and playlistName.
- [x] Playlists shared with that user should be rendered in a list including the playlist's name, the user who shared the playlist, and the date of the share. 
- [x] Improve the styling of the list.
- [x] Playlists shared with that user should be sorted in reverse chronological order.
- [x] Playlists they have not yet seen should be in bold.
- [x] Import a modal component from material-ui into `shares.js`
- [x] Clicking on a shared playlist should initiate a modal with the name of the playlist and the user who shared it so users can confirm they want to add the playlist.
- [x] Add a 'confirm' button to the modal.
- [x] Clicking on the button should update the `seen` status in the MongoDB database to be true.
- [x] After a playlist is `seen`, the app should refetch the number of unseen playlists.
- [x] App should not fetch user's unseen playlists before the user logs in.
- [x] Fix bug where UserAvatar doesn't update view to `shares` if there are no unseen shares.
- [x] Clicking on the button should initiate a fetch call to the Spotify API that causes the user to follow the playlist.
- [x] User sees a confirmation message that they have followed the playlist.
- [x] After 1.5 seconds, app state is updated to the playlists view.
