### ISSUE TITLE
Add fallback image for songs without images; style refactor.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#35]
# Motivation
The app currently crashes if a song in a playlist does not have an image.

# Tasks
- [ ] Import an icon from Material-UI to use as a placeholder song image.
- [ ] Add conditional that checks for presence of a song's image and renders the placeholder if none is found.
- [ ] Improve styling to make it consistent with other song images.
## Refactor tasks
- [ ] App state should take a `selectedPlaylist` object instead of separate selectedPlaylistId and selectedPlaylistName.
- [ ] App state should take a `user` object instead of separate userName and userId.
- [ ] Destructure variables from this.props and this.state throughout code.
