### ISSUE TITLE
User can authorize the app to be them on Spotify. (Oauth)

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#5]
## Motivation
We want the user to be able to log in to their Spotify service so we can get their user data.

## Tasks
- [x] Configure linters for project. 
- [x] Express server hosts a static index.html.
- [x] Index.html displays a simple button for users to initiate a login.
- [x] Clicking the button initiates a request to Spotify's authorization service.
- [x] Express authorization requests successfully receives a code from the Spotify API.
- [x] Express server successfully re-routes the code to Spotify's API to receive refresh and access tokens.
- [x] Express server utilizes access token to get user data from the Spotify API.
- [x] User display_name, email, access token, refresh token, and user uri are stored in a MongoDB database.
- [x] _Current User's information is persisted as JSON to server/cookies. (undone)_
- [x] Current User's token is redirected in url to browser instead of persisted as JSON.
- [x] Refactor index.html to utilize a single-page React app.
- [x] Create a logo for Social Spotify.
- [x] Index.html displays a logo and styles the button for users to initiate a login to Spotify.
- [x] Add a background image and improve overall styling of the page.
### Refactor 1 Tasks
- [x] Regenerate Private Spotify Client Secret and save it to an .env file.
- [x] Remove console.logs.
- [x] Utilize request-promise instead of request to avoid mixing callbacks and promises.
- [x] Redirect the client back to the browser _after_ the database is updated.
- [x] Server should respond to client even in error cases.
