### ISSUE TITLE
User can view songs in a playlist.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#7]
## Motivation
User needs to be able to select a playlist and see songs that are a part of it.

## Tasks
- [x] Add user image to the information stored in MongoDB.
- [x] Create a React Component to hold the user image.
- [x] Embed the user image into the component by passing it as a prop to src.
- [x] Component should be positioned in the upper right hand corner of the screen.
- [x] Selected playlist is added as a property of the App state.
- [x] Clicking on a playlist fetches its ID from the array of playlists and updates the app state accordingly.
- [x] Clicking on a playlist changes the view to `songs`. 
- [x] Playlist ID is sent to the Spotify API, which returns a list of songs in the playlist.
- [x] Songs and their associated artists are rendered in a list to the app.
- [x] Improve visual styling of the list of songs.
### Refactor Tasks
- [x] Create a PageHeader component to hold the floated avatar.
- [x] Remove the 'new-block-formatting-context' class and inline the style to the PageHeader component.
- [x] Replace playlists.js and songs.js index identifiers with unique identifiers.
- [x] Declare the base URL for spotify in a constants.js and update app throughout.
