### ISSUE TITLE
User can share a playlist with another user.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/social-spotify#8]
## Motivation
Users will want to share a playlist with other users so that other users can rate the songs on the playlist.

## Tasks
- [x] Create a wireframe.
- [x] Find a 'share' icon from Material UI and import it into the PageHeader component.
- [x] Float the icon to match the existing buttons.
- [x] Improve styling of the button.
- [x] Clicking the share button changes the view state to 'users'.
- [x] Selected playlist ID is passed as props to the user view component.
- [x] Clicking on the back button in 'users' view returns the user to 'songs' view.
- [x] Write express route to return other users from 'users' collection in MongoDB database.
- [x] App no longer crashes if user does not have a profile picture set.
- [x] App displays placeholder user icon if no user image is set.
- [x] App displays 'User has no playlists' if user does not have playlists.
- [x] Refactor default account image to render as part of the UserAvatar instead of part of the PageHeader.
- [x] Upon mount of 'users' view, send fetch request to express route to get list of users.
- [x] Render each user's name and avatar.
- [x] Improve visual styling of the list.
- [x] Clicking on a user initiates a Modal with the name of the playlist and the user.
- [x] Modal should display name of playlist instead of playlist ID.
- [x] Add a button to the Modal to 'confirm' the desired share.
- [x] Improve styling of the modal.
- [x] Create Express.js route to handle sender's user id, recipient's user id, playlist id, and current time to a database of 'shares'.
- [x] Clicking on the button sends a fetch request to the 'shares' route with the sender's user id, recipient's user id, and playlist id.
- [x] After sharing, user sees a confirmation message that the playlist has been successfully shared and is returned to playlist view.
- [x] User-list should send a GET request for users rather than a POST request.

## Wireframe
<img width="676" alt="screen shot 2018-11-02 at 10 49 43" src="https://user-images.githubusercontent.com/39274776/47931790-1b070500-de8d-11e8-9fc5-101ff117b0ae.png">
<img width="683" alt="screen shot 2018-11-02 at 10 49 53" src="https://user-images.githubusercontent.com/39274776/47931791-1b9f9b80-de8d-11e8-8790-7fe6e2fdd023.png">
<img width="681" alt="screen shot 2018-11-02 at 10 50 10" src="https://user-images.githubusercontent.com/39274776/47931793-1b9f9b80-de8d-11e8-9c04-73a2a768b86b.png">
